// Code generated by "stringer -type CrossChainStatusType"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CrossChainStatusTypeUnknown-0]
	_ = x[CrossChainStatusTypeInvalid-1]
	_ = x[CrossChainStatusTypeValid-2]
}

const _CrossChainStatusType_name = "CrossChainStatusTypeUnknownCrossChainStatusTypeInvalidCrossChainStatusTypeValid"

var _CrossChainStatusType_index = [...]uint8{0, 27, 54, 79}

func (i CrossChainStatusType) String() string {
	if i < 0 || i >= CrossChainStatusType(len(_CrossChainStatusType_index)-1) {
		return "CrossChainStatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CrossChainStatusType_name[_CrossChainStatusType_index[i]:_CrossChainStatusType_index[i+1]]
}
