// Code generated by "stringer -type ETHAmountStatus"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ETHAmountStatusTypeUnset-0]
	_ = x[ETHAmountStatusTypeSet-1]
}

const _ETHAmountStatus_name = "ETHAmountStatusTypeUnsetETHAmountStatusTypeSet"

var _ETHAmountStatus_index = [...]uint8{0, 24, 46}

func (i ETHAmountStatus) String() string {
	if i < 0 || i >= ETHAmountStatus(len(_ETHAmountStatus_index)-1) {
		return "ETHAmountStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ETHAmountStatus_name[_ETHAmountStatus_index[i]:_ETHAmountStatus_index[i+1]]
}
