// Code generated by "stringer -type ETHBalanceStatus"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ETHBalanceStatusTypeInvalid-0]
	_ = x[ETHBalanceStatusTypeValid-1]
}

const _ETHBalanceStatus_name = "ETHBalanceStatusTypeInvalidETHBalanceStatusTypeValid"

var _ETHBalanceStatus_index = [...]uint8{0, 27, 52}

func (i ETHBalanceStatus) String() string {
	if i < 0 || i >= ETHBalanceStatus(len(_ETHBalanceStatus_index)-1) {
		return "ETHBalanceStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ETHBalanceStatus_name[_ETHBalanceStatus_index[i]:_ETHBalanceStatus_index[i+1]]
}
