// Code generated by "stringer -type=EventType -output=eventtype_string.go event.go"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventTypeUnknown-0]
	_ = x[L1SentMessage-1]
	_ = x[L1RelayedMessage-2]
	_ = x[L2SentMessage-3]
	_ = x[L2RelayedMessage-4]
	_ = x[L1DepositETH-5]
	_ = x[L1FinalizeWithdrawETH-6]
	_ = x[L1RefundETH-7]
	_ = x[L2FinalizeDepositETH-8]
	_ = x[L2WithdrawETH-9]
	_ = x[L1DepositERC20-10]
	_ = x[L1FinalizeWithdrawERC20-11]
	_ = x[L1RefundERC20-12]
	_ = x[L2FinalizeDepositERC20-13]
	_ = x[L2WithdrawERC20-14]
	_ = x[L1DepositERC721-15]
	_ = x[L1FinalizeWithdrawERC721-16]
	_ = x[L1RefundERC721-17]
	_ = x[L2FinalizeDepositERC721-18]
	_ = x[L2WithdrawERC721-19]
	_ = x[L1DepositERC1155-20]
	_ = x[L1FinalizeWithdrawERC1155-21]
	_ = x[L1RefundERC1155-22]
	_ = x[L2FinalizeDepositERC1155-23]
	_ = x[L2WithdrawERC1155-24]
	_ = x[L1BatchDepositERC721-25]
	_ = x[L1FinalizeBatchWithdrawERC721-26]
	_ = x[L1BatchRefundERC721-27]
	_ = x[L2FinalizeBatchDepositERC721-28]
	_ = x[L2BatchWithdrawERC721-29]
	_ = x[L1BatchDepositERC1155-30]
	_ = x[L1FinalizeBatchWithdrawERC1155-31]
	_ = x[L1BatchRefundERC1155-32]
	_ = x[L2FinalizeBatchDepositERC1155-33]
	_ = x[L2BatchWithdrawERC1155-34]
}

const _EventType_name = "EventTypeUnknownL1SentMessageL1RelayedMessageL2SentMessageL2RelayedMessageL1DepositETHL1FinalizeWithdrawETHL1RefundETHL2FinalizeDepositETHL2WithdrawETHL1DepositERC20L1FinalizeWithdrawERC20L1RefundERC20L2FinalizeDepositERC20L2WithdrawERC20L1DepositERC721L1FinalizeWithdrawERC721L1RefundERC721L2FinalizeDepositERC721L2WithdrawERC721L1DepositERC1155L1FinalizeWithdrawERC1155L1RefundERC1155L2FinalizeDepositERC1155L2WithdrawERC1155L1BatchDepositERC721L1FinalizeBatchWithdrawERC721L1BatchRefundERC721L2FinalizeBatchDepositERC721L2BatchWithdrawERC721L1BatchDepositERC1155L1FinalizeBatchWithdrawERC1155L1BatchRefundERC1155L2FinalizeBatchDepositERC1155L2BatchWithdrawERC1155"

var _EventType_index = [...]uint16{0, 16, 29, 45, 58, 74, 86, 107, 118, 138, 151, 165, 188, 201, 223, 238, 253, 277, 291, 314, 330, 346, 371, 386, 410, 427, 447, 476, 495, 523, 544, 565, 595, 615, 644, 666}

func (i EventType) String() string {
	if i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
