// Code generated by "stringer -type EventType"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventTypeUnknown-0]
	_ = x[L1DepositETH-1]
	_ = x[L1FinalizeWithdrawETH-2]
	_ = x[L1RefundETH-3]
	_ = x[L1DepositWETH-4]
	_ = x[L1FinalizeWithdrawWETH-5]
	_ = x[L1RefundWETH-6]
	_ = x[L2FinalizeDepositETH-7]
	_ = x[L2WithdrawETH-8]
	_ = x[L1DepositDAI-9]
	_ = x[L1FinalizeWithdrawDAI-10]
	_ = x[L1DepositStandardERC20-11]
	_ = x[L1FinalizeWithdrawStandardERC20-12]
	_ = x[L1DepositCustomERC20-13]
	_ = x[L1FinalizeWithdrawCustomERC20-14]
	_ = x[L1USDCDepositERC20-15]
	_ = x[L1USDCFinalizeWithdrawERC20-16]
	_ = x[L1LIDODepositERC20-17]
	_ = x[L1LIDOFinalizeWithdrawERC20-18]
	_ = x[L2FinalizeDepositWETH-19]
	_ = x[L2WithdrawWETH-20]
	_ = x[L2FinalizeDepositDAI-21]
	_ = x[L2WithdrawDAI-22]
	_ = x[L2FinalizeDepositStandardERC20-23]
	_ = x[L2WithdrawStandardERC20-24]
	_ = x[L2FinalizeDepositCustomERC20-25]
	_ = x[L2WithdrawCustomERC20-26]
	_ = x[L2USDCWithdrawERC20-27]
	_ = x[L2USDCFinalizeDepositERC20-28]
	_ = x[L2LIDOWithdrawERC20-29]
	_ = x[L2LIDOFinalizeDepositERC20-30]
	_ = x[L1DepositERC721-31]
	_ = x[L1FinalizeWithdrawERC721-32]
	_ = x[L2FinalizeDepositERC721-33]
	_ = x[L2WithdrawERC721-34]
	_ = x[L1DepositERC1155-35]
	_ = x[L1FinalizeWithdrawERC1155-36]
	_ = x[L2FinalizeDepositERC1155-37]
	_ = x[L2WithdrawERC1155-38]
}

const _EventType_name = "EventTypeUnknownL1DepositETHL1FinalizeWithdrawETHL1RefundETHL1DepositWETHL1FinalizeWithdrawWETHL1RefundWETHL2FinalizeDepositETHL2WithdrawETHL1DepositDAIL1FinalizeWithdrawDAIL1DepositStandardERC20L1FinalizeWithdrawStandardERC20L1DepositCustomERC20L1FinalizeWithdrawCustomERC20L1USDCDepositERC20L1USDCFinalizeWithdrawERC20L1LIDODepositERC20L1LIDOFinalizeWithdrawERC20L2FinalizeDepositWETHL2WithdrawWETHL2FinalizeDepositDAIL2WithdrawDAIL2FinalizeDepositStandardERC20L2WithdrawStandardERC20L2FinalizeDepositCustomERC20L2WithdrawCustomERC20L2USDCWithdrawERC20L2USDCFinalizeDepositERC20L2LIDOWithdrawERC20L2LIDOFinalizeDepositERC20L1DepositERC721L1FinalizeWithdrawERC721L2FinalizeDepositERC721L2WithdrawERC721L1DepositERC1155L1FinalizeWithdrawERC1155L2FinalizeDepositERC1155L2WithdrawERC1155"

var _EventType_index = [...]uint16{0, 16, 28, 49, 60, 73, 95, 107, 127, 140, 152, 173, 195, 226, 246, 275, 293, 320, 338, 365, 386, 400, 420, 433, 463, 486, 514, 535, 554, 580, 599, 625, 640, 664, 687, 703, 719, 744, 768, 785}

func (i EventType) String() string {
	if i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
