// Code generated by "stringer -type LayerType"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LayerUnknown-0]
	_ = x[Layer1-1]
	_ = x[Layer2-2]
}

const _LayerType_name = "LayerUnknownLayer1Layer2"

var _LayerType_index = [...]uint8{0, 12, 18, 24}

func (i LayerType) String() string {
	if i < 0 || i >= LayerType(len(_LayerType_index)-1) {
		return "LayerType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LayerType_name[_LayerType_index[i]:_LayerType_index[i+1]]
}
