.PHONY: scroll

scroll:
	# L1
	./build_abi.sh L1
	# L1/gateway
	./build_abi.sh L1/gateway
	# L1/rollup
	./build_abi.sh L1/rollup
	# L2
	./build_abi.sh L2
	# L2/gateway
	./build_abi.sh L2/gateway
	# token
	./build_abi.sh token
