name: Docker

on:
  push:
    tags:
      - v**

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          # push: ${{ startsWith(github.ref, 'refs/tags/') }}
          push: true
          tags: scrolltech/chain-monitorv2:${{github.ref_name}}
          # cache-from: type=gha,scope=${{ github.workflow }}
          # cache-to: type=gha,scope=${{ github.workflow }}
